version: "3.7"

services:

  app:
    build: './app'
    container_name: 'mahigoliapp'
    restart: 'always'
    expose:
      - '8000'
    environment:
      - "POSTGRES_DB=django_mahigoli"
      - "POSTGRES_USER=mahigoli_user"
      - "POSTGRES_PASSWORD=1234"
      - "POSTGRES_HOST=postgresdb"
      - "POSTGRES_PORT=5432"
    volumes:
      - type: 'bind'
        source: './volumes/app'
        target: '/app'
    depends_on:
      - 'nginx'
      - 'postgresdb'

  nginx:
    build: './nginx'
    container_name: 'nginx'
    restart: 'always'
    ports:
      - '80:80'
    volumes:
      - type: 'bind'
        source: './volumes/static'
        target: '/app/static'

      - type: 'bind'
        source: './volumes/media'
        target: '/app/media'

  postgresdb:
    image: 'postgres:alpine'
    container_name: 'postgresdb'
    restart: 'always'
    expose:
      - '5432'
    volumes:
      - type: 'bind'
        source: './volumes/dbdata'
        target: '/var/lib/postgresql/data'
    environment:
      - "POSTGRES_DB=django_mahigoli"
      - "POSTGRES_USER=mahigoli_user"
      - "POSTGRES_PASSWORD=1234"