# Generated by Django 3.2.10 on 2022-03-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='الزامی', max_length=254, unique=True, verbose_name='ایمیل'),
        ),
    ]
