# Generated by Django 3.2.10 on 2022-01-29 17:09

import book.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75, verbose_name='نام')),
                ('middle_name', models.CharField(blank=True, default='', max_length=75, verbose_name='نام میانی')),
                ('last_name', models.CharField(max_length=75, verbose_name='نام خانوادگی')),
                ('avatar', models.ImageField(blank=True, upload_to='./images/person/', verbose_name='عکس پروفایل')),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسندگان',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, null=True, verbose_name='دسته\u200cبندی')),
                ('parent', models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='book.category', verbose_name='زیردسته')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='نام')),
                ('url', models.URLField(max_length=256, verbose_name='وب سایت')),
            ],
            options={
                'verbose_name': 'ناشر',
                'verbose_name_plural': 'ناشرین',
            },
        ),
        migrations.CreateModel(
            name='Teller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75, verbose_name='نام')),
                ('middle_name', models.CharField(blank=True, default='', max_length=75, verbose_name='نام میانی')),
                ('last_name', models.CharField(max_length=75, verbose_name='نام خانوادگی')),
                ('avatar', models.ImageField(blank=True, upload_to='./images/person/', verbose_name='عکس پروفایل')),
            ],
            options={
                'verbose_name': 'گوینده',
                'verbose_name_plural': 'گویندگان',
            },
        ),
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75, verbose_name='نام')),
                ('middle_name', models.CharField(blank=True, default='', max_length=75, verbose_name='نام میانی')),
                ('last_name', models.CharField(max_length=75, verbose_name='نام خانوادگی')),
                ('avatar', models.ImageField(blank=True, upload_to='./images/person/', verbose_name='عکس پروفایل')),
            ],
            options={
                'verbose_name': 'مترجم',
                'verbose_name_plural': 'مترجمان',
            },
        ),
        migrations.CreateModel(
            name='PhysicalBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1500, verbose_name='نام کتاب')),
                ('language_book', models.CharField(blank=True, choices=[('eng', 'انگلیسی'), ('per', 'فارسی')], default=None, max_length=3, null=True, verbose_name='زبان کتاب')),
                ('rate', models.SmallIntegerField(blank=True, choices=[(1, 'بد'), (2, 'بد نبود'), (3, 'معمولی'), (4, 'خوب'), (5, 'عالی')], null=True, verbose_name='امتیاز')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='قیمت')),
                ('price_unit', models.CharField(choices=[('FRE', 'رایگان'), ('IRR', 'ریال ایران'), ('USD', 'دلار آمریکا'), ('GBP', 'پوند انگلیس'), ('CAD', 'دلار کانادا'), ('AUD', 'دلار استرالیا')], default='FRE', max_length=3, verbose_name='واحد پول')),
                ('user_description', models.TextField(blank=True, null=True, verbose_name='توضیحات کاربر درباره کتاب')),
                ('book_description', models.TextField(blank=True, default=None, null=True, verbose_name='توضیحات کتاب')),
                ('book_url', models.URLField(blank=True, default=None, max_length=1024, null=True)),
                ('pages_readed', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='صفحات خوانده شده')),
                ('pages', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد صفحات کتاب')),
                ('read_flag', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('platform', models.CharField(blank=True, choices=[('borro', 'قرض گرفته شده'), ('prlib', 'کتابخانه شخصی'), ('pulib', 'کتابخانه عمومی')], max_length=5, null=True, verbose_name='منبع کتاب')),
                ('author', models.ManyToManyField(to='book.Author', verbose_name='نویسنده')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.category', verbose_name='دسته\u200cبندی')),
                ('translator', models.ManyToManyField(blank=True, to='book.Translator', verbose_name='مترجم')),
            ],
            options={
                'verbose_name': 'کتاب فیزیکی',
                'verbose_name_plural': 'کتب فیزیکی',
            },
        ),
        migrations.CreateModel(
            name='ElectronicBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1500, verbose_name='نام کتاب')),
                ('language_book', models.CharField(blank=True, choices=[('eng', 'انگلیسی'), ('per', 'فارسی')], default=None, max_length=3, null=True, verbose_name='زبان کتاب')),
                ('rate', models.SmallIntegerField(blank=True, choices=[(1, 'بد'), (2, 'بد نبود'), (3, 'معمولی'), (4, 'خوب'), (5, 'عالی')], null=True, verbose_name='امتیاز')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='قیمت')),
                ('price_unit', models.CharField(choices=[('FRE', 'رایگان'), ('IRR', 'ریال ایران'), ('USD', 'دلار آمریکا'), ('GBP', 'پوند انگلیس'), ('CAD', 'دلار کانادا'), ('AUD', 'دلار استرالیا')], default='FRE', max_length=3, verbose_name='واحد پول')),
                ('user_description', models.TextField(blank=True, null=True, verbose_name='توضیحات کاربر درباره کتاب')),
                ('book_description', models.TextField(blank=True, default=None, null=True, verbose_name='توضیحات کتاب')),
                ('book_url', models.URLField(blank=True, default=None, max_length=1024, null=True)),
                ('pages_readed', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='صفحات خوانده شده')),
                ('pages', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد صفحات کتاب')),
                ('read_flag', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('book_file', models.FileField(blank=True, null=True, upload_to='./book_files/', validators=[book.models.ebook_file_format_validator])),
                ('platform', models.CharField(blank=True, choices=[('taghc', 'طاقچه'), ('ketab', 'کتابراه'), ('fidib', 'فیدیبو'), ('booka', 'بوکاپو'), ('teleg', 'تلگرام'), ('websi', 'وب سایت'), ('prlib', 'کتابخانه شخصی'), ('pulib', 'کتابخانه عمومی')], max_length=5, null=True, verbose_name='منبع کتاب')),
                ('author', models.ManyToManyField(to='book.Author', verbose_name='نویسنده')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.category', verbose_name='دسته\u200cبندی')),
                ('translator', models.ManyToManyField(blank=True, to='book.Translator', verbose_name='مترجم')),
            ],
            options={
                'verbose_name': 'کتاب الکترونیکی',
                'verbose_name_plural': 'کتب الکترونیکی',
            },
        ),
        migrations.CreateModel(
            name='AudioBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1500, verbose_name='نام کتاب')),
                ('language_book', models.CharField(blank=True, choices=[('eng', 'انگلیسی'), ('per', 'فارسی')], default=None, max_length=3, null=True, verbose_name='زبان کتاب')),
                ('rate', models.SmallIntegerField(blank=True, choices=[(1, 'بد'), (2, 'بد نبود'), (3, 'معمولی'), (4, 'خوب'), (5, 'عالی')], null=True, verbose_name='امتیاز')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='قیمت')),
                ('price_unit', models.CharField(choices=[('FRE', 'رایگان'), ('IRR', 'ریال ایران'), ('USD', 'دلار آمریکا'), ('GBP', 'پوند انگلیس'), ('CAD', 'دلار کانادا'), ('AUD', 'دلار استرالیا')], default='FRE', max_length=3, verbose_name='واحد پول')),
                ('user_description', models.TextField(blank=True, null=True, verbose_name='توضیحات کاربر درباره کتاب')),
                ('book_description', models.TextField(blank=True, default=None, null=True, verbose_name='توضیحات کتاب')),
                ('book_url', models.URLField(blank=True, default=None, max_length=1024, null=True)),
                ('episode', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='قسمت')),
                ('season', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='فصل')),
                ('listen_flag', models.BooleanField(default=False, verbose_name='گوش داده شده')),
                ('platform', models.CharField(blank=True, choices=[('taghc', 'طاقچه'), ('ketab', 'کتابراه'), ('fidib', 'فیدیبو'), ('booka', 'بوکاپو'), ('teleg', 'تلگرام'), ('websi', 'وب سایت'), ('castb', 'کست باکس')], max_length=5, null=True, verbose_name='منبع کتاب')),
                ('book_file', models.FileField(blank=True, null=True, upload_to='./book_files/', validators=[book.models.audiobook_file_format_validator])),
                ('author', models.ManyToManyField(to='book.Author', verbose_name='نویسنده')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.category', verbose_name='دسته\u200cبندی')),
                ('teller', models.ManyToManyField(blank=True, to='book.Teller', verbose_name='گوینده')),
                ('translator', models.ManyToManyField(blank=True, to='book.Translator', verbose_name='مترجم')),
            ],
            options={
                'verbose_name': 'کتاب صوتی',
                'verbose_name_plural': 'کتب صوتی',
            },
        ),
    ]
