# Generated by Django 3.2.10 on 2022-01-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20220115_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75, verbose_name='نام')),
                ('middle_name', models.CharField(max_length=75, verbose_name='نام میانی')),
                ('last_name', models.CharField(max_length=75, verbose_name='نام خانوادگی')),
                ('avatar', models.ImageField(upload_to='./images/person/', verbose_name='عکس پروفایل')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75, verbose_name='نام')),
                ('middle_name', models.CharField(max_length=75, verbose_name='نام میانی')),
                ('last_name', models.CharField(max_length=75, verbose_name='نام خانوادگی')),
                ('avatar', models.ImageField(upload_to='./images/person/', verbose_name='عکس پروفایل')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
