# Generated by Django 3.2.10 on 2022-01-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20220129_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiobook',
            name='listen_flag',
        ),
        migrations.RemoveField(
            model_name='electronicbook',
            name='read_flag',
        ),
        migrations.RemoveField(
            model_name='physicalbook',
            name='read_flag',
        ),
        migrations.AddField(
            model_name='audiobook',
            name='listen_status',
            field=models.CharField(choices=[('U', 'خوانده نشده'), ('L', 'در حال مطالعه'), ('H', 'خوانده شده')], default='U', max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='electronicbook',
            name='read_status',
            field=models.CharField(choices=[('U', 'خوانده نشده'), ('S', 'در حال مطالعه'), ('R', 'خوانده شده')], default='U', max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='physicalbook',
            name='read_status',
            field=models.CharField(choices=[('U', 'خوانده نشده'), ('S', 'در حال مطالعه'), ('R', 'خوانده شده')], default='U', max_length=1, verbose_name='وضعیت'),
        ),
    ]
