# Generated by Django 3.2.10 on 2022-01-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20220116_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=75, verbose_name='نام میانی'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=75, verbose_name='نام میانی'),
        ),
    ]
