# Generated by Django 3.2.10 on 2022-02-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_audiobook_listen_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiobook',
            name='picture',
            field=models.ImageField(blank=True, upload_to='./images/books/', verbose_name='تصویر جلد'),
        ),
        migrations.AddField(
            model_name='electronicbook',
            name='picture',
            field=models.ImageField(blank=True, upload_to='./images/books/', verbose_name='تصویر جلد'),
        ),
        migrations.AddField(
            model_name='physicalbook',
            name='picture',
            field=models.ImageField(blank=True, upload_to='./images/books/', verbose_name='تصویر جلد'),
        ),
    ]
