# Generated by Django 3.2.10 on 2022-02-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20220201_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='listen_status',
            field=models.CharField(choices=[('U', 'شنیده نشده'), ('L', 'در حال شنیدن'), ('H', 'شنیده شده'), ('M', 'نشان شده')], default='U', max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='price_unit',
            field=models.CharField(choices=[('FRE', '---'), ('IRR', 'تومان ایران'), ('USD', 'دلار آمریکا'), ('GBP', 'پوند انگلیس'), ('CAD', 'دلار کانادا'), ('AUD', 'دلار استرالیا')], default='FRE', max_length=3, verbose_name='واحد پول'),
        ),
        migrations.AlterField(
            model_name='electronicbook',
            name='price_unit',
            field=models.CharField(choices=[('FRE', '---'), ('IRR', 'تومان ایران'), ('USD', 'دلار آمریکا'), ('GBP', 'پوند انگلیس'), ('CAD', 'دلار کانادا'), ('AUD', 'دلار استرالیا')], default='FRE', max_length=3, verbose_name='واحد پول'),
        ),
        migrations.AlterField(
            model_name='electronicbook',
            name='read_status',
            field=models.CharField(choices=[('U', 'خوانده نشده'), ('S', 'در حال مطالعه'), ('R', 'خوانده شده'), ('M', 'نشان شده')], default='U', max_length=1, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='physicalbook',
            name='price_unit',
            field=models.CharField(choices=[('FRE', '---'), ('IRR', 'تومان ایران'), ('USD', 'دلار آمریکا'), ('GBP', 'پوند انگلیس'), ('CAD', 'دلار کانادا'), ('AUD', 'دلار استرالیا')], default='FRE', max_length=3, verbose_name='واحد پول'),
        ),
        migrations.AlterField(
            model_name='physicalbook',
            name='read_status',
            field=models.CharField(choices=[('U', 'خوانده نشده'), ('S', 'در حال مطالعه'), ('R', 'خوانده شده'), ('M', 'نشان شده')], default='U', max_length=1, verbose_name='وضعیت'),
        ),
    ]
