# Generated by Django 3.2.10 on 2022-01-16 15:56

import book.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20220116_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='نام کتاب')),
                ('language_book', models.CharField(choices=[('eng', 'english'), ('per', 'persian')], default='per', max_length=3)),
                ('book_url', models.URLField(default=None, max_length=1024)),
                ('book_file', models.FileField(upload_to='./book_files/', validators=[book.models.file_format_validator])),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت')),
                ('user_description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('rate', models.SmallIntegerField(blank=True, choices=[(1, 'tribble'), (2, 'not bad'), (3, 'ordinary'), (4, 'good'), (5, 'excellent')], null=True, verbose_name='امتیاز')),
                ('book_type', models.CharField(choices=[('a', 'audio'), ('p', 'physical'), ('e', 'electronic')], max_length=1, verbose_name='نوع کتاب')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.author', verbose_name='نویسنده')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.category', verbose_name='دسته\u200cبندی')),
                ('translator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.translator', verbose_name='مترجم')),
            ],
            options={
                'verbose_name': 'کتاب',
                'verbose_name_plural': 'کتب',
            },
        ),
    ]
