# Generated by Django 3.2.10 on 2022-01-16 15:59

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_file',
            field=models.FileField(blank=True, upload_to='./book_files/', validators=[book.models.file_format_validator]),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_url',
            field=models.URLField(blank=True, default=None, max_length=1024, null=True),
        ),
    ]
