# Generated by Django 3.2.10 on 2022-02-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20220202_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='book_url',
            field=models.URLField(blank=True, default=None, max_length=1024, null=True, verbose_name='آدرس اینترنتی'),
        ),
        migrations.AlterField(
            model_name='electronicbook',
            name='book_url',
            field=models.URLField(blank=True, default=None, max_length=1024, null=True, verbose_name='آدرس اینترنتی'),
        ),
        migrations.AlterField(
            model_name='physicalbook',
            name='book_url',
            field=models.URLField(blank=True, default=None, max_length=1024, null=True, verbose_name='آدرس اینترنتی'),
        ),
    ]
