# Generated by Django 3.2.10 on 2022-01-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20220116_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('a', 'صوتی'), ('p', 'فیزیکی'), ('e', 'الکترونیکی')], max_length=1, verbose_name='نوع کتاب'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language_book',
            field=models.CharField(choices=[('eng', 'انگلیسی'), ('per', 'فارسی')], default='per', max_length=3),
        ),
        migrations.AlterField(
            model_name='book',
            name='rate',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'بد'), (2, 'بد نبود'), (3, 'معمولی'), (4, 'خوب'), (5, 'عالی')], null=True, verbose_name='امتیاز'),
        ),
    ]
