# Generated by Django 3.2.10 on 2022-01-16 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20220116_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=75, verbose_name='نام')),
                ('middle_name', models.CharField(blank=True, default='', max_length=75, verbose_name='نام میانی')),
                ('last_name', models.CharField(max_length=75, verbose_name='نام خانوادگی')),
                ('avatar', models.ImageField(blank=True, upload_to='./images/person/', verbose_name='عکس پروفایل')),
            ],
            options={
                'verbose_name': 'گوینده',
                'verbose_name_plural': 'گویندگان',
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='book.Author', verbose_name='نویسنده'),
        ),
        migrations.AddField(
            model_name='book',
            name='teller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.teller', verbose_name='مترجم'),
        ),
    ]
