# Generated by Django 3.2.10 on 2022-03-08 09:52

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20220226_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiobook',
            name='book_file',
            field=models.FileField(blank=True, null=True, upload_to='audiobook_files/', validators=[book.models.audiobook_file_format_validator]),
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images/books/', verbose_name='تصویر جلد'),
        ),
        migrations.AlterField(
            model_name='author',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='images/person/', verbose_name='عکس پروفایل'),
        ),
        migrations.AlterField(
            model_name='electronicbook',
            name='book_file',
            field=models.FileField(blank=True, null=True, upload_to='electronicbook_files/', validators=[book.models.ebook_file_format_validator]),
        ),
        migrations.AlterField(
            model_name='electronicbook',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images/books/', verbose_name='تصویر جلد'),
        ),
        migrations.AlterField(
            model_name='physicalbook',
            name='picture',
            field=models.ImageField(blank=True, upload_to='images/books/', verbose_name='تصویر جلد'),
        ),
        migrations.AlterField(
            model_name='teller',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='images/person/', verbose_name='عکس پروفایل'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='images/person/', verbose_name='عکس پروفایل'),
        ),
    ]
