# Generated by Django 3.2.10 on 2022-01-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_auto_20220116_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='teller',
        ),
        migrations.AddField(
            model_name='book',
            name='teller',
            field=models.ManyToManyField(blank=True, null=True, to='book.Teller', verbose_name='مترجم'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='translator',
        ),
        migrations.AddField(
            model_name='book',
            name='translator',
            field=models.ManyToManyField(blank=True, null=True, to='book.Translator', verbose_name='مترجم'),
        ),
    ]
