# Generated by Django 3.2.10 on 2022-01-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_auto_20220116_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('a', 'صوتی'), ('p', 'فیزیکی'), ('e', 'الکترونیکی')], default='e', max_length=1, verbose_name='نوع کتاب'),
        ),
    ]
