# Generated by Django 3.2.10 on 2022-01-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_alter_book_book_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='نام')),
                ('url', models.URLField(max_length=256, verbose_name='وب سایت')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='book_description',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='توضیحات کتاب'),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد صفحات کتاب'),
        ),
        migrations.AddField(
            model_name='book',
            name='pages_readed',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='صفحات خوانده شده'),
        ),
        migrations.AddField(
            model_name='book',
            name='platform',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='منبع کتاب'),
        ),
        migrations.AddField(
            model_name='book',
            name='price_unit',
            field=models.CharField(choices=[('IRR', 'ریال ایران'), ('USD', 'دلار آمریکا'), ('GBP', 'پوند انگلیس'), ('CAD', 'دلار کانادا'), ('AUD', 'دلار استرالیا')], default='IRR', max_length=3, verbose_name='واحد پول'),
        ),
        migrations.AlterField(
            model_name='book',
            name='user_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات کاربر درباره کتاب'),
        ),
    ]
