# Generated by Django 3.2.10 on 2022-01-25 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_auto_20220117_0847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publisher',
            options={'verbose_name': 'ناشر', 'verbose_name_plural': 'ناشرین'},
        ),
    ]
