# Generated by Django 3.2.10 on 2022-01-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_alter_publisher_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='books', to='book.Author', verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='book',
            name='platform',
            field=models.CharField(blank=True, choices=[('taghc', 'طاقچه'), ('ketab', 'کتابراه'), ('teleg', 'تلگرام'), ('websi', 'وب سایت'), ('prlib', 'کتابخانه شخصی'), ('pulib', 'کتابخانه عمومی')], max_length=5, null=True, verbose_name='منبع کتاب'),
        ),
    ]
