# Generated by Django 3.2.10 on 2022-01-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0019_auto_20220126_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language_book',
            field=models.CharField(choices=[('eng', 'انگلیسی'), ('per', 'فارسی')], default='per', max_length=3, verbose_name='زبان کتاب'),
        ),
    ]
