from django.urls import path
from .views import (
    AllBook,
    PhysicalBookList,
    ElectronicBookList,
    AudioBookList,
    AuthorList,
    TranslatorList,
    TellerList,
    PublisherList,
    CategoryList,
    PhysicalBookCreate,
    ElectronicBookCreate,
    AudioBookCreate,
    PhysicalBookUpdate,
    ElectronicBookUpdate,
    AudioBookUpdate,
    PhysicalBookDelete,
    ElectronicBookDelete,
)

app_name = 'book'
urlpatterns = [
    path('', AllBook.as_view(), name='allbook'),
    path('physicalbook/', PhysicalBookList.as_view(), name='physicalbook'),
    path('electronicbook/', ElectronicBookList.as_view(), name='electronicbook'),
    path('audiobook/', AudioBookList.as_view(), name='audiobook'),
    path('author/', AuthorList.as_view(), name='author'),
    path('translator/', TranslatorList.as_view(), name='translator'),
    path('teller/', TellerList.as_view(), name='teller'),
    path('publisher/', PublisherList.as_view(), name='publisher'),
    path('category/', CategoryList.as_view(), name='category'),
    path('physicalbook/create/', PhysicalBookCreate.as_view(), name='physicalbook_create'),
    path('physicalbook/update/<int:pk>', PhysicalBookUpdate.as_view(), name='physicalbook_update'),
    path('physicalbook/delete/<int:pk>', PhysicalBookDelete.as_view(), name='physicalbook_delete'),
    path('electronicbook/create/', ElectronicBookCreate.as_view(), name='electronicbook_create'),
    path('electronicbook/update/<int:pk>', ElectronicBookUpdate.as_view(), name='electronicbook_update'),
    path('electronicbook/delete/<int:pk>', ElectronicBookDelete.as_view(), name='electronicbook_delete'),
    path('audiobook/create/', AudioBookCreate.as_view(), name='audiobook_create'),
    path('audiobook/update/<int:pk>', AudioBookUpdate.as_view(), name='audiobook_update'),
]