from django.urls import path
from .views import (
    AllBook,
    PhysicalBookList,
    ElectronicBookList,
    AudioBookList,
    AuthorList,
    TranslatorList,
    TellerList,
    PublisherList,
    CategoryList,
    PhysicalBookCreate,
    ElectronicBookCreate,
    AudioBookCreate,
    PhysicalBookUpdate,
    ElectronicBookUpdate,
    AudioBookUpdate,
    PhysicalBookDelete,
    ElectronicBookDelete,
    AudioBookDelete,
    AuthorCreate,
    TranslatorCreate,
    TellerCreate,
    AuthorUpdate,
    TranslatorUpdate,
    TellerUpdate,
    AuthorDelete,
    TranslatorDelete,
    TellerDelete,
    CategoryCreate,
)

app_name = 'book'
urlpatterns = [
    path('', AllBook.as_view(), name='allbook'),
    path('physicalbook/', PhysicalBookList.as_view(), name='physicalbook'),
    path('physicalbook/create/', PhysicalBookCreate.as_view(), name='physicalbook_create'),
    path('physicalbook/update/<int:pk>', PhysicalBookUpdate.as_view(), name='physicalbook_update'),
    path('physicalbook/delete/<int:pk>', PhysicalBookDelete.as_view(), name='physicalbook_delete'),
    path('electronicbook/', ElectronicBookList.as_view(), name='electronicbook'),
    path('electronicbook/create/', ElectronicBookCreate.as_view(), name='electronicbook_create'),
    path('electronicbook/update/<int:pk>', ElectronicBookUpdate.as_view(), name='electronicbook_update'),
    path('electronicbook/delete/<int:pk>', ElectronicBookDelete.as_view(), name='electronicbook_delete'),
    path('audiobook/', AudioBookList.as_view(), name='audiobook'),
    path('audiobook/create/', AudioBookCreate.as_view(), name='audiobook_create'),
    path('audiobook/update/<int:pk>', AudioBookUpdate.as_view(), name='audiobook_update'),
    path('audiobook/delete/<int:pk>', AudioBookDelete.as_view(), name='audiobook_delete'),
    path('author/', AuthorList.as_view(), name='author'),
    path('author/create/', AuthorCreate.as_view(), name='author_create'),
    path('author/update/<int:pk>', AuthorUpdate.as_view(), name='author_update'),
    path('author/delete/<int:pk>', AuthorDelete.as_view(), name='author_delete'),
    path('translator/', TranslatorList.as_view(), name='translator'),
    path('translator/create', TranslatorCreate.as_view(), name='translator_create'),
    path('translator/update/<int:pk>', TranslatorUpdate.as_view(), name='translator_update'),
    path('translator/delete/<int:pk>', TranslatorDelete.as_view(), name='translator_delete'),
    path('teller/', TellerList.as_view(), name='teller'),
    path('teller/create', TellerCreate.as_view(), name='teller_create'),
    path('teller/update/<int:pk>', TellerUpdate.as_view(), name='teller_update'),
    path('teller/delete/<int:pk>', TellerDelete.as_view(), name='teller_delete'),
    path('publisher/', PublisherList.as_view(), name='publisher'),
    path('category/', CategoryList.as_view(), name='category'),
    path('category/create/', CategoryCreate.as_view(), name='category_create'),
]