from django.urls import path
from .views import (
    HomeView,
    AllBookView,
    PhysicalBookListView,
    ElectronicBookListView,
    AudioBookListView,
    AuthorListView,
    TranslatorListView,
    TellerListView,
    PublisherListView,
    CategoryListView,
    PhysicalBookCreateView,
    ElectronicBookCreateView,
    AudioBookCreateView,
    PhysicalBookUpdateView,
    ElectronicBookUpdateView,
    AudioBookUpdateView,
    PhysicalBookDeleteView,
    ElectronicBookDeleteView,
    AudioBookDeleteView,
    AuthorCreateView,
    TranslatorCreateView,
    TellerCreateView,
    AuthorUpdateView,
    TranslatorUpdateView,
    TellerUpdateView,
    AuthorDeleteView,
    TranslatorDeleteView,
    TellerDeleteView,
    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView,
    PublisherCreateView,
    PublisherUpdateView,
    PublisherDeleteView,
)

app_name = 'book'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('books/', AllBookView.as_view(), name='allbook'),
    path('physicalbook/', PhysicalBookListView.as_view(), name='physicalbook'),
    path('physicalbook/create/', PhysicalBookCreateView.as_view(), name='physicalbook_create'),
    path('physicalbook/update/<int:pk>', PhysicalBookUpdateView.as_view(), name='physicalbook_update'),
    path('physicalbook/delete/<int:pk>', PhysicalBookDeleteView.as_view(), name='physicalbook_delete'),
    path('electronicbook/', ElectronicBookListView.as_view(), name='electronicbook'),
    path('electronicbook/create/', ElectronicBookCreateView.as_view(), name='electronicbook_create'),
    path('electronicbook/update/<int:pk>', ElectronicBookUpdateView.as_view(), name='electronicbook_update'),
    path('electronicbook/delete/<int:pk>', ElectronicBookDeleteView.as_view(), name='electronicbook_delete'),
    path('audiobook/', AudioBookListView.as_view(), name='audiobook'),
    path('audiobook/create/', AudioBookCreateView.as_view(), name='audiobook_create'),
    path('audiobook/update/<int:pk>', AudioBookUpdateView.as_view(), name='audiobook_update'),
    path('audiobook/delete/<int:pk>', AudioBookDeleteView.as_view(), name='audiobook_delete'),
    path('author/', AuthorListView.as_view(), name='author'),
    path('author/create/', AuthorCreateView.as_view(), name='author_create'),
    path('author/update/<int:pk>', AuthorUpdateView.as_view(), name='author_update'),
    path('author/delete/<int:pk>', AuthorDeleteView.as_view(), name='author_delete'),
    path('translator/', TranslatorListView.as_view(), name='translator'),
    path('translator/create', TranslatorCreateView.as_view(), name='translator_create'),
    path('translator/update/<int:pk>', TranslatorUpdateView.as_view(), name='translator_update'),
    path('translator/delete/<int:pk>', TranslatorDeleteView.as_view(), name='translator_delete'),
    path('teller/', TellerListView.as_view(), name='teller'),
    path('teller/create', TellerCreateView.as_view(), name='teller_create'),
    path('teller/update/<int:pk>', TellerUpdateView.as_view(), name='teller_update'),
    path('teller/delete/<int:pk>', TellerDeleteView.as_view(), name='teller_delete'),
    path('publisher/', PublisherListView.as_view(), name='publisher'),
    path('publisher/create/', PublisherCreateView.as_view(), name='publisher_create'),
    path('publisher/update/<int:pk>', PublisherUpdateView.as_view(), name='publisher_update'),
    path('publisher/delete/<int:pk>', PublisherDeleteView.as_view(), name='publisher_delete'),
    path('category/', CategoryListView.as_view(), name='category'),
    path('category/create/', CategoryCreateView.as_view(), name='category_create'),
    path('category/update/<int:pk>', CategoryUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:pk>', CategoryDeleteView.as_view(), name='category_delete'),
]